export type Profile = {
  slug: string;
  name: string;
  image: string;
  rating: string;
  time: string;
  country: string;
  tzs: string;
  usd: string;
  intro: string;
  replies: string[];
};

export const profiles: Profile[] = [
  { slug: "ivan", name: "Ivan", image: "https://randomuser.me/api/portraits/men/32.jpg", rating: "4.9", time: "2 hours", country: "USA 🇺🇸", tzs: "80,183", usd: "32.09", intro: "Hello! I am learning Swahili and I would love to practice a little with you.", replies: ["That sounds good. What does that sentence mean in natural Swahili?", "Nice! Can you teach me one everyday phrase I could use with a friend?", "I understand now. Is there another way a Tanzanian would normally say it?", "Great lesson. I like learning the meaning and the pronunciation together."] },
  { slug: "angelica", name: "Angélica", image: "https://randomuser.me/api/portraits/women/44.jpg", rating: "4.8", time: "1 hour 30 minutes", country: "Australia 🇦🇺", tzs: "73,826", usd: "28.02", intro: "Hi! I am from Australia. I want to become more comfortable speaking Swahili.", replies: ["Could you explain that word with a simple example?", "Perfect, I will try it again. Please correct me if my Swahili sounds unnatural.", "What would you say when greeting a new friend in Tanzania?", "Thank you! I am starting to understand the difference between the words now."] },
  { slug: "carmen", name: "Carmen", image: "https://randomuser.me/api/portraits/women/8.jpg", rating: "4.6", time: "40 minutes", country: "Canada 🇨🇦", tzs: "41,743", usd: "16.37", intro: "Hello! I am practicing Swahili for travel and everyday conversations.", replies: ["Can we practice a short conversation about ordering food?", "That example helps a lot. How would I say it politely?", "Let me try: I want to learn Swahili every day. Is that correct?", "Awesome, I will remember that phrase."] },
  { slug: "dejalme", name: "Dejalme", image: "https://randomuser.me/api/portraits/men/93.jpg", rating: "4.5", time: "1 hour 30 minutes", country: "Switzerland 🇨🇭", tzs: "73,826", usd: "28.02", intro: "Hi! I enjoy learning languages. Today I want to practice simple Swahili conversation.", replies: ["Please tell me what that means word by word.", "Could you give me a more casual version that friends would use?", "I like that expression. When is it appropriate to use it?", "Excellent. I will practice that sentence again."] },
  { slug: "evencio", name: "Evêncio", image: "https://randomuser.me/api/portraits/men/49.jpg", rating: "4.7", time: "1 hour", country: "Japan 🇯🇵", tzs: "51,089", usd: "19.91", intro: "Hello! I am studying Swahili and I want to improve my daily speaking.", replies: ["Interesting. Can you show me how to use that phrase in a normal chat?", "Thank you. I will repeat it slowly so I can remember the pronunciation.", "What is a friendly way to ask someone how their day was?", "That makes sense now. Please give me one more example."] },
  { slug: "riley", name: "Riley", image: "https://randomuser.me/api/portraits/men/53.jpg", rating: "5.0", time: "1 hour 10 minutes", country: "Norway 🇳🇴", tzs: "67,303", usd: "24.43", intro: "Hi there! I am learning Swahili because I enjoy East African culture.", replies: ["Can you teach me a phrase I could use when meeting someone for the first time?", "That is helpful. What is the natural reply to that greeting?", "I think I got it. Let me try another sentence.", "Nice correction. I can hear the difference now."] },
  { slug: "arquimedes", name: "Arquimedes", image: "https://randomuser.me/api/portraits/men/59.jpg", rating: "5.0", time: "2 hours", country: "Germany 🇩🇪", tzs: "87,945", usd: "32.31", intro: "Hello! I am interested in learning useful Swahili for daily life.", replies: ["What would a local usually say in that situation?", "Can you explain the tone? I want to sound friendly, not too formal.", "Great, I will use that version. What should I learn next?", "That is much clearer. Thanks for teaching me."] },
  { slug: "nino", name: "Nino", image: "https://randomuser.me/api/portraits/women/89.jpg", rating: "5.0", time: "30 minutes", country: "Brazil 🇧🇷", tzs: "32,704", usd: "11.31", intro: "Hi! I am learning Swahili for fun. Can we have a simple conversation?", replies: ["Haha, I like that! What is the Swahili word for that idea?", "Please correct my sentence and tell me how a native speaker would say it.", "I am enjoying this. Give me another short phrase to practice.", "Perfect! I think I can remember that one."] },
  { slug: "grace", name: "Grace", image: "https://randomuser.me/api/portraits/women/68.jpg", rating: "4.7", time: "25 minutes", country: "UK 🇬🇧", tzs: "25,817", usd: "10.25", intro: "Hello! I am practicing beginner Swahili. Please keep the conversation simple.", replies: ["Thank you. Could you say that in an easier way?", "I understand. What is the polite version of that sentence?", "Let me practice: habari yako? Did I say it correctly?", "Great! I feel more confident already."] },
  { slug: "antonin", name: "Antonin", image: "https://randomuser.me/api/portraits/men/72.jpg", rating: "4.6", time: "40 minutes", country: "France 🇫🇷", tzs: "41,909", usd: "15.60", intro: "Bonjour! I am learning Swahili and would like to practice everyday phrases.", replies: ["What does that expression literally mean?", "Can you give me an example from a normal conversation?", "I will try to use it now. Please tell me if I make a mistake.", "Excellent. I learned something useful today."] },
];

export const profileBySlug = (slug: string) => profiles.find((profile) => profile.slug === slug);
